# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'calculator.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(416, 394)
        Form.setStyleSheet(u"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(110, 0, 201, 41))
        font = QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.btn_3 = QPushButton(Form)
        self.btn_3.setObjectName(u"btn_3")
        self.btn_3.setGeometry(QRect(170, 190, 71, 41))
        font1 = QFont()
        font1.setPointSize(16)
        self.btn_3.setFont(font1)
        self.btn_3.setStyleSheet(u"border: 1px solid white;")
        self.btn_6 = QPushButton(Form)
        self.btn_6.setObjectName(u"btn_6")
        self.btn_6.setGeometry(QRect(170, 140, 71, 41))
        self.btn_6.setFont(font1)
        self.btn_6.setStyleSheet(u"border: 1px solid white;")
        self.btn_7 = QPushButton(Form)
        self.btn_7.setObjectName(u"btn_7")
        self.btn_7.setGeometry(QRect(10, 90, 71, 41))
        self.btn_7.setFont(font1)
        self.btn_7.setStyleSheet(u"border: 1px solid white;")
        self.btn_multiply = QPushButton(Form)
        self.btn_multiply.setObjectName(u"btn_multiply")
        self.btn_multiply.setGeometry(QRect(250, 190, 71, 41))
        self.btn_multiply.setFont(font1)
        self.btn_multiply.setStyleSheet(u"border: 1px solid white;\n"
"")
        self.btn_0 = QPushButton(Form)
        self.btn_0.setObjectName(u"btn_0")
        self.btn_0.setGeometry(QRect(90, 240, 71, 41))
        self.btn_0.setFont(font1)
        self.btn_0.setStyleSheet(u"border: 1px solid white;\n"
"")
        self.btn_add = QPushButton(Form)
        self.btn_add.setObjectName(u"btn_add")
        self.btn_add.setGeometry(QRect(250, 140, 71, 41))
        self.btn_add.setFont(font1)
        self.btn_add.setStyleSheet(u"border: 1px solid white;")
        self.btn_equal = QPushButton(Form)
        self.btn_equal.setObjectName(u"btn_equal")
        self.btn_equal.setGeometry(QRect(250, 240, 151, 41))
        self.btn_equal.setFont(font1)
        self.btn_equal.setStyleSheet(u"border: 1px solid white;")
        self.btn_delete = QPushButton(Form)
        self.btn_delete.setObjectName(u"btn_delete")
        self.btn_delete.setGeometry(QRect(250, 90, 71, 41))
        self.btn_delete.setFont(font1)
        self.btn_delete.setStyleSheet(u"border: 1px solid white;")
        self.btn_2 = QPushButton(Form)
        self.btn_2.setObjectName(u"btn_2")
        self.btn_2.setGeometry(QRect(90, 190, 71, 41))
        self.btn_2.setFont(font1)
        self.btn_2.setStyleSheet(u"border: 1px solid white;")
        self.btn_5 = QPushButton(Form)
        self.btn_5.setObjectName(u"btn_5")
        self.btn_5.setGeometry(QRect(90, 140, 71, 41))
        self.btn_5.setFont(font1)
        self.btn_5.setStyleSheet(u"border: 1px solid white;")
        self.btn_9 = QPushButton(Form)
        self.btn_9.setObjectName(u"btn_9")
        self.btn_9.setGeometry(QRect(170, 90, 71, 41))
        self.btn_9.setFont(font1)
        self.btn_9.setStyleSheet(u"border: 1px solid white;")
        self.lineEdit = QLineEdit(Form)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 40, 391, 41))
        self.lineEdit.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border: 1px solid gray;")
        self.btn_8 = QPushButton(Form)
        self.btn_8.setObjectName(u"btn_8")
        self.btn_8.setGeometry(QRect(90, 90, 71, 41))
        self.btn_8.setFont(font1)
        self.btn_8.setStyleSheet(u"border: 1px solid white;")
        self.btn_4 = QPushButton(Form)
        self.btn_4.setObjectName(u"btn_4")
        self.btn_4.setGeometry(QRect(10, 140, 71, 41))
        self.btn_4.setFont(font1)
        self.btn_4.setStyleSheet(u"border: 1px solid white;")
        self.btn_1 = QPushButton(Form)
        self.btn_1.setObjectName(u"btn_1")
        self.btn_1.setGeometry(QRect(10, 190, 71, 41))
        self.btn_1.setFont(font1)
        self.btn_1.setStyleSheet(u"border: 1px solid white;")
        self.btn_dot = QPushButton(Form)
        self.btn_dot.setObjectName(u"btn_dot")
        self.btn_dot.setGeometry(QRect(10, 240, 71, 41))
        self.btn_dot.setFont(font1)
        self.btn_dot.setStyleSheet(u"border: 1px solid white;")
        self.btn_reset = QPushButton(Form)
        self.btn_reset.setObjectName(u"btn_reset")
        self.btn_reset.setGeometry(QRect(330, 90, 71, 41))
        self.btn_reset.setFont(font1)
        self.btn_reset.setStyleSheet(u"background-color: rgb(255, 170, 0);")
        self.btn_divide = QPushButton(Form)
        self.btn_divide.setObjectName(u"btn_divide")
        self.btn_divide.setGeometry(QRect(330, 190, 71, 41))
        self.btn_divide.setFont(font1)
        self.btn_divide.setStyleSheet(u"border: 1px solid white;")
        self.btn_minus = QPushButton(Form)
        self.btn_minus.setObjectName(u"btn_minus")
        self.btn_minus.setGeometry(QRect(330, 140, 71, 41))
        self.btn_minus.setFont(font1)
        self.btn_minus.setStyleSheet(u"border: 1px solid white;")
        self.btn_mod = QPushButton(Form)
        self.btn_mod.setObjectName(u"btn_mod")
        self.btn_mod.setGeometry(QRect(170, 240, 71, 41))
        self.btn_mod.setFont(font1)
        self.btn_mod.setStyleSheet(u"border: 1px solid white;")
        self.btn_cos = QPushButton(Form)
        self.btn_cos.setObjectName(u"btn_cos")
        self.btn_cos.setGeometry(QRect(140, 340, 131, 41))
        self.btn_cos.setFont(font1)
        self.btn_cos.setStyleSheet(u"border: 1px solid white;")
        self.btn_tan = QPushButton(Form)
        self.btn_tan.setObjectName(u"btn_tan")
        self.btn_tan.setGeometry(QRect(280, 340, 121, 41))
        self.btn_tan.setFont(font1)
        self.btn_tan.setStyleSheet(u"border: 1px solid white;")
        self.btn_sin = QPushButton(Form)
        self.btn_sin.setObjectName(u"btn_sin")
        self.btn_sin.setGeometry(QRect(10, 340, 121, 41))
        self.btn_sin.setFont(font1)
        self.btn_sin.setStyleSheet(u"border: 1px solid white;")
        self.btn_pi = QPushButton(Form)
        self.btn_pi.setObjectName(u"btn_pi")
        self.btn_pi.setGeometry(QRect(170, 290, 71, 41))
        self.btn_pi.setFont(font1)
        self.btn_pi.setStyleSheet(u"border-color: rgb(255, 255, 255);\n"
"border: 1px solid white;")
        self.btn_sqrt = QPushButton(Form)
        self.btn_sqrt.setObjectName(u"btn_sqrt")
        self.btn_sqrt.setGeometry(QRect(330, 290, 71, 41))
        self.btn_sqrt.setFont(font1)
        self.btn_sqrt.setStyleSheet(u"border: 1px solid white;")
        self.btn_curly_close = QPushButton(Form)
        self.btn_curly_close.setObjectName(u"btn_curly_close")
        self.btn_curly_close.setGeometry(QRect(90, 290, 71, 41))
        self.btn_curly_close.setFont(font1)
        self.btn_curly_close.setStyleSheet(u"border: 1px solid white;")
        self.btn_curly_open = QPushButton(Form)
        self.btn_curly_open.setObjectName(u"btn_curly_open")
        self.btn_curly_open.setGeometry(QRect(10, 290, 71, 41))
        self.btn_curly_open.setFont(font1)
        self.btn_curly_open.setStyleSheet(u"border: 1px solid white;")
        self.btn_pow = QPushButton(Form)
        self.btn_pow.setObjectName(u"btn_pow")
        self.btn_pow.setGeometry(QRect(250, 290, 71, 41))
        self.btn_pow.setFont(font1)
        self.btn_pow.setStyleSheet(u"border-color: rgb(255, 255, 255);\n"
"border: 1px solid white;")

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"CALCULATOR", None))
        self.btn_3.setText(QCoreApplication.translate("Form", u"3", None))
        self.btn_6.setText(QCoreApplication.translate("Form", u"6", None))
        self.btn_7.setText(QCoreApplication.translate("Form", u"7", None))
        self.btn_multiply.setText(QCoreApplication.translate("Form", u"*", None))
        self.btn_0.setText(QCoreApplication.translate("Form", u"0", None))
        self.btn_add.setText(QCoreApplication.translate("Form", u"+", None))
        self.btn_equal.setText(QCoreApplication.translate("Form", u"=", None))
        self.btn_delete.setText(QCoreApplication.translate("Form", u"<", None))
        self.btn_2.setText(QCoreApplication.translate("Form", u"2", None))
        self.btn_5.setText(QCoreApplication.translate("Form", u"5", None))
        self.btn_9.setText(QCoreApplication.translate("Form", u"9", None))
        self.btn_8.setText(QCoreApplication.translate("Form", u"8", None))
        self.btn_4.setText(QCoreApplication.translate("Form", u"4", None))
        self.btn_1.setText(QCoreApplication.translate("Form", u"1", None))
        self.btn_dot.setText(QCoreApplication.translate("Form", u".", None))
        self.btn_reset.setText(QCoreApplication.translate("Form", u"AC", None))
        self.btn_divide.setText(QCoreApplication.translate("Form", u"/", None))
        self.btn_minus.setText(QCoreApplication.translate("Form", u"-", None))
        self.btn_mod.setText(QCoreApplication.translate("Form", u"%", None))
        self.btn_cos.setText(QCoreApplication.translate("Form", u"cos", None))
        self.btn_tan.setText(QCoreApplication.translate("Form", u"tan", None))
        self.btn_sin.setText(QCoreApplication.translate("Form", u"sin", None))
        self.btn_pi.setText(QCoreApplication.translate("Form", u"pi", None))
        self.btn_sqrt.setText(QCoreApplication.translate("Form", u"sqrt", None))
        self.btn_curly_close.setText(QCoreApplication.translate("Form", u")", None))
        self.btn_curly_open.setText(QCoreApplication.translate("Form", u"(", None))
        self.btn_pow.setText(QCoreApplication.translate("Form", u"^", None))
    # retranslateUi

